---
services:
  code-server:
    build:
      context: ./code-server # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile # Specify the Dockerfile name
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - 'code-server-config:/config'
# volumes:
#   code-server-config: # Define the named volume
#     driver: local